### ISSUE TITLE
Example for a zebra-type puzzle?

### ISSUE THREAD

**Issue by rschwiebert** [pythological/kanren#51]
Recently I found an example [here](https://github.com/MNoorFawi/logic-programming-in-python) which purported to solve a "zebra puzzle" using python's kanren library.  Its syntax is obviously broken now, and if it had worked under a previous version of the library with an older version of python, I did not check.  This is as fixed as I can get it:

```
from kanren import run, eq, lall, membero, var, conde


# first define the right function which will set something to the right side of other things
def right(x, y, lst):
    return membero((x, y), zip(lst[1:], lst))


# nextto function will check if two things nextto to each other
def nextto(x, y, lst):
    # they are nextto to each other if x is to y right OR y is to x right
    return conde([right(x, y, lst)], [right(y, x, lst)])


# houses
houses = var()

# puzzle rules
zebra_riddle = lall(
    # houses is equal to 5 var as there are 5 houses
    eq((var(), var(), var(), var(), var()), houses),
    # house members
    membero(('Englishman', var(), var(), var(), 'red'), houses),
    membero(('Spaniard', var(), var(), 'dog', var()), houses),
    membero(('Ukrainian', var(), 'tea', var(), var()), houses),
    # put to the right
    # right((var(), var(), var(), var(), 'ivory'), (var(), var(), var(), var(), 'green'), houses),
    membero((var(), var(), 'coffee', var(), 'green'), houses),
    membero((var(), 'Old Gold', var(), 'snails', var()), houses),
    membero((var(), 'Kools', var(), var(), 'yellow'), houses),
    # define the milk house as a 5-var tuple in the middle of the 5-var houses
    eq((var(), var(), (var(), var(), 'milk', var(), var()), var(), var()), houses),
    # the same with the Norwegian in the first
    eq((('Norwegian', var(), var(), var(), var()), var(), var(), var(), var()), houses),
    # check nextto to
    nextto( (var(), 'Chesterfield', var(), var(), var()), (var(), var(), var(), 'fox', var()), houses),
    nextto((var(), 'Kools', var(), var(), var()), (var(), var(), var(), 'horse', var()), houses),
    membero((var(), 'Lucky Strike', 'Orange Juice', var(), var()), houses),
    membero(('Japanese', "Parliaments", var(), var(), var()), houses),
    nextto(('Norwegian', var(), var(), var(), var()), (var(), var(), var(), var(), 'blue'), houses),
    # insert the water and zebra houses
    membero((var(), var(), "water", var(), var()), houses),
    membero((var(), var(), var(), 'zebra', var()), houses)
)

if __name__ == '__main__':
    # run the rules to see the houses structures.
    solutions = run(1, houses, zebra_riddle)
    breakpoint()
```

If I try to uncomment the goal with `right` (or any of the `nextto`s for that matter because they depend on `right`) we get 
```
Traceback (most recent call last):
  File "/Users/.../PycharmProjects/datalog/minikanren/zebra.py", line 36, in <module>
    nextto( (var(), 'Chesterfield', var(), var(), var()), (var(), var(), var(), 'fox', var()), houses),
  File "/Users/.../PycharmProjects/datalog/minikanren/zebra.py", line 12, in nextto
    return conde([right(x, y, lst)], [right(y, x, lst)])
  File "/Users/.../PycharmProjects/datalog/minikanren/zebra.py", line 6, in right
    return membero((x, y), zip(lst[1:], lst))
TypeError: 'Var' object is not subscriptable
```
because `lst` is apparently a Var and not an iterable of Var so that `lst[1:]` would work. I think the program expected this to be resolved as (unified into?) a list of Var in the first `eq` goal.  

I also tried starting with `houses = (var(), var(), var(), var(), var())` and forgoing the `eq` goal to try to get around this, but when I do that it results in no solutions when I comment in any of the `right` or `nextto` lines.

I also tried
```
houses = (
    ('Norwegian', var(), var(), var(), var()),
    (var(), var(), var(), var(), var()),
    (var(), var(), 'milk', var(), var()),
    (var(), var(), var(), var(), var()),
    (var(), var(), var(), var(), var()),
)
```
and apparently then `right` works as written, but it also eliminates all solutions, so something is wrong.

Can you advise on how to fix this?

More generally, your examples section could use expansion.  [This repo of examples](https://github.com/MNoorFawi/logic-programming-in-python) would have a solid selection of examples, if only they actually worked with today's version of kanren.  Without examples of that detail it's really hard for a new person like me to pick up this API at a reasonable rate.  Thanks for your attention!

**Comment by rlouf** [comment]
Thank you for opening an issue. Adding simple examples is a good idea, I'll take a look at your problem this week.

**Comment by rschwiebert** [comment]
Thank you for posting that example! I hope it goes into the examples directory of this repo as well.

As for the code I was working with: on a hunch I wrapped the `zip` in `list` and it started working!

**Comment by rschwiebert** [comment]
Here's the fixed version of my earlier code.   I know the published solution is already another one, but I figured I'd add it for completeness.
```
from kanren import run, eq, lall, membero, var, conde, vars


# first define the right function which will set something to the right side of other things
def right(x, y, lst):
    return membero((x, y), list(zip(lst[1:], lst)))


# nextto function will check if two things nextto to each other
def nextto(x, y, lst):
    # they are nextto to each other if x is to y right OR y is to x right
    return conde([right(x, y, lst)], [right(y, x, lst)])


# houses
houses = vars(5)

# puzzle rules
zebra_riddle = lall(
    # house members
    membero(('Englishman', var(), var(), var(), 'red'), houses),
    membero(('Spaniard', var(), var(), 'dog', var()), houses),
    membero(('Ukrainian', var(), 'tea', var(), var()), houses),
    membero((var(), var(), var(), var(), 'ivory'), houses),

    # put to the right
    right((var(), var(), var(), var(), 'ivory'), (var(), var(), var(), var(), 'green'), houses),
    membero((var(), var(), 'coffee', var(), 'green'), houses),
    membero((var(), 'Old Gold', var(), 'snails', var()), houses),
    membero((var(), 'Kools', var(), var(), 'yellow'), houses),
    # define the milk house as a 5-var tuple in the middle of the 5-var houses
    eq((var(), var(), 'milk', var(), var()), houses[2]),
    # the same with the Norwegian in the first
    eq(('Norwegian', var(), var(), var(), var()), houses[0]),
    # check nextto to
    nextto( (var(), 'Chesterfield', var(), var(), var()), (var(), var(), var(), 'fox', var()), houses),
    nextto((var(), 'Kools', var(), var(), var()), (var(), var(), var(), 'horse', var()), houses),
    membero((var(), 'Lucky Strike', 'Orange Juice', var(), var()), houses),
    membero(('Japanese', "Parliaments", var(), var(), var()), houses),
    nextto(('Norwegian', var(), var(), var(), var()), (var(), var(), var(), var(), 'blue'), houses),
    # insert the water and zebra houses
    membero((var(), var(), "water", var(), var()), houses),
    membero((var(), var(), var(), 'zebra', var()), houses)
)

if __name__ == '__main__':
    # run the rules to see the houses structures.
    solutions = run(0, houses, zebra_riddle)
    
```
